name: Deploy to develop

on:
  push:
    branches:
      - "develop"

jobs:
  redeploy_frontend:
    name: Deploy frontend to develop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH Into Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 139.59.19.212
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /thirdx/thirdxui
            git stash
            git fetch --all
            git checkout develop
            git pull origin develop
            git log -1
            npm install -f
            npm run build | tee build.log

